### ISSUE TITLE
Unable to use Streamie

### ISSUE THREAD

**Issue by hellowahab** [cramforce/streamie#61]
Getting following error
C:\Program Files\nodejs\streamie\lib>node server.js
The "sys" module is now called "util". It should have a similar interface.

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (C:\Program Files\nodejs\streamie\lib\server.js:3:12)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)

C:\Program Files\nodejs\streamie\lib>node server.js
The "sys" module is now called "util". It should have a similar interface.

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (C:\Program Files\nodejs\streamie\lib\server.js:3:12)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)

Can anybody help me ?

**Comment by badboy** [comment]
Your missing the dependencies, especially `socket.io`, so do:

```
npm install
```

**Comment by hellowahab** [comment]
What I did, i installed node.js for window and make a simple example working.
Then i get the streamie code from git repository and moved it inside node.js folder
Now when i try to run ->node server.js and i get above mentioned error.

**Comment by badboy** [comment]
No need to move streamie into the node.js folder.
But as I said for streamie to work you need the dependencies, so you have to install them. See the [Setup info](https://github.com/cramforce/streamie#setup) in the README (there are a few other steps, for example getting oAuth secrets from twitter)

If all this setup is to much and you just want to use streamie for tweeting you can always use the hosted version: https://streamie.org/

**Comment by hellowahab** [comment]
After trying each and everything is am still on the same issue.
I meant to work with code not just browsing so using web url is not an option.

**Comment by badboy** [comment]
Still the same error message? If so, that means you're still missing some dependencies.
I'm not sure if the current code works for your own use, but there is a third option: After forking this repository here on github you can visit your own version of streamie on `<username>.streamie.org`
